package com.yosha10.final_project.core.utils

object RegionID {
    const val ACEH = "ID-AC"
    const val BALI = "ID-BA"
    const val BANGKA_BELITUNG = "ID-BB"
    const val BANTEN = "ID-BT"
    const val BENGKULU = "ID-BE"
    const val JAWA_TENGAH = "ID-JT"
    const val KALIMANTAN_TENGAH = "ID-KT"
    const val SULAWESI_TENGAH = "ID-ST"
    const val JAWA_TIMUR = "ID-JI"
    const val KALIMANTAN_TIMUR = "ID-KI"
    const val NUSA_TENGGARA_TIMUR = "ID-NT"
    const val GORONTALO = "ID-GO"
    const val DKI_JAKARTA = "ID-JK"
    const val JAMBI = "ID-JA"
    const val LAMPUNG = "ID-LA"
    const val MALUKU = "ID-MA"
    const val KALIMANTAN_UTARA = "ID-KU"
    const val MALUKU_UTARA = "ID-MU"
    const val SULAWESI_UTARA = "ID-SA"
    const val SUMATERA_UTARA = "ID-SU"
    const val PAPUA = "ID-PA"
    const val RIAU = "ID-RI"
    const val KEPULAUAN_RIAU = "ID-KR"
    const val SULAWESI_TENGGARA = "ID-SG"
    const val KALIMANTAN_SELATAN = "ID-KS"
    const val SULAWESI_SELATAN = "ID-SN"
    const val SUMATERA_SELATAN = "ID-SS"
    const val DI_YOGYAKARTA = "ID-YO"
    const val JAWA_BARAT = "ID-JB"
    const val KALIMANTAN_BARAT = "ID-KB"
    const val NUSA_TENGGARA_BARAT = "ID-NB"
    const val PAPUA_BARAT = "ID-PB"
    const val SULAWESI_BARAT = "ID-SR"
    const val SUMATERA_BARAT = "ID-SB"
}
